### ISSUE TITLE
Calendar not showing up in Google

### ISSUE THREAD

**Issue by malcolmjay** [DOKOS-IO/gcalendar#1]
I've passed on the correct client and secret information and created a new account.  The new calendar I created doesn't appear to be creating a new calendar in Google.  Whenever I reload the GCalendar settings page, it comes back as "Not Saved" even though I saved it.  Not sure if this is a bug\\
![image](https://user-images.githubusercontent.com/35127786/36636924-eb025470-1995-11e8-9c7d-e02be61a4e37.png)

**Comment by chdecultot** [comment]
Hi @malcolmjay,

I just retested on another server and there was indeed an issue with the connector (a dev key that I forgot to replace...)
Can you update your application and check again please ?

After adding your credentials here, you should create a new account for your user in GCalendar Accounts (make sure the browser allows popups):

1. You will be asked for your Google Account:
![image](https://user-images.githubusercontent.com/4903591/36729647-2d014760-1bc5-11e8-9a7c-9693d15bd36a.png)

2. You will be asked to validate the autorizations given to your Google Cloud Application:
![image](https://user-images.githubusercontent.com/4903591/36729693-54e5cb02-1bc5-11e8-8ebb-58aa36ea6983.png)

3. You will be redirected to a blank page:
![image](https://user-images.githubusercontent.com/4903591/36729723-675060a4-1bc5-11e8-9169-b24645526263.png)
(I need to work on this last redirection to make it sweeter).

Make sure your scheduler is enabled and you should see the configured agenda appear in Google Calendar after a few minutes:
![image](https://user-images.githubusercontent.com/4903591/36730481-ddd3cd90-1bc7-11e8-9237-9f5ec6209967.png)


You can check the Error Log and Background Jobs logs for more information if it doesn't work ("Setup > Error Log" or "Developer > Background Jobs")

Thanks a lot for your help and feedback!

**Comment by chdecultot** [comment]
hi @malcolmjay,

Have you been able to connect to your Google Calendar account ?

Make sure to update the application, because I have made some modifications to correct several bugs.

I'm closing this issue for now, don't hesitate to open a new if needed.

Best regards!
