### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by viitaset** [DOKOS-IO/gcalendar#2]
Hi, thanks for a great module for ERPNext!

I have a problem regarding timezone conversion. I added a calendar event inside google calendar and started to get these errors in Error Log:

```
{'retry': 0, 'log': <function log at 0x7fc5fe6472a8>, 'site': u'dev.fullmetal.group', 'event': None, 'method_name': u'frappe.utils.background_jobs.run_doc_method', 'method': <function run_doc_method at 0x7fc5fef65cf8>, 'user': u'Administrator', 'kwargs': {'doc_method': u'run_current_mapping', 'name': u'15cb5ca3e7', 'doctype': u'Data Migration Run'}, 'async': True, 'job_name': u'frappe.utils.background_jobs.run_doc_method'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 97, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 76, in run_doc_method
    getattr(frappe.get_doc(doctype, name), doc_method)(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/data_migration/doctype/data_migration_run/data_migration_run.py", line 75, in run_current_mapping
    raise e
ValueError: astimezone() cannot be applied to a naive datetime
```

I think this has something to do about timezone aware vs naive datetime?

Thanks in advance!

**Comment by chdecultot** [comment]
Hi @viitaset,

Thanks for reporting, I'll look into it!

**Comment by chdecultot** [comment]
Hi @viitaset, sorry for the very late reply.

I have pushed a fix to Frappe directly (https://github.com/frappe/frappe/pull/5571) as this connector has been merged in Frappe and will be available in version 11.

I will therefore deprecate this application, but don't hesitate to open issues linked to the connector here if you like.

Thanks again for your support.
