### ISSUE TITLE
NOT working 

### ISSUE THREAD

**Issue by kingt0t** [DOKOS-IO/gcalendar#3]
doesn't work fresh install 
showed nothing 

![screen shot 2018-08-25 at 3 29 35 pm](https://user-images.githubusercontent.com/15651426/44618289-8ae88600-a873-11e8-870b-b45436ba6702.png)

**Comment by chdecultot** [comment]
Hi  @kingt0t,

This application is deprecated as it has been integrated directly into ERPNext and is available in version 11.

This repository is only available as a reference.

Thanks for your interest anyway!
